### ISSUE TITLE
ERROR in GraphSage

### ISSUE THREAD

**Issue by KomachiZ** [huunghia160799/CS224W-Stanford#1]
hi, When I finish the hw2"GraphSage" ,I meet the same error which is ”TypeError: Required parameter edge_index is empty.“ in your code "hw2-model.py" ，So I wanna get a help from you how to fix it, thanks!

Traceback (most recent call last):
  File "/Users/yukino/Documents/DLspace/CS224W/hw2-bundle/q4_starter_code/train.py", line 134, in <module>
    main()
  File "/Users/yukino/Documents/DLspace/CS224W/hw2-bundle/q4_starter_code/train.py", line 129, in main
    train(dataset, task, args) 
  File "/Users/yukino/Documents/DLspace/CS224W/hw2-bundle/q4_starter_code/train.py", line 78, in train
    pred = model(batch)
  File "/Users/yukino/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yukino/Documents/DLspace/CS224W/hw2-bundle/q4_starter_code/models.py", line 51, in forward
    x = self.convs[i](x,edge_index)
  File "/Users/yukino/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yukino/Documents/DLspace/CS224W/hw2-bundle/q4_starter_code/models.py", line 107, in forward
    return self.propagate(edge_index, size=(num_nodes, num_nodes), x=out)
  File "/Users/yukino/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 257, in propagate
    msg_kwargs = self.__distribute__(self.__msg_params__, kwargs)
  File "/Users/yukino/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 180, in __distribute__
    raise TypeError(f'Required parameter {key} is empty.')
TypeError: Required parameter edge_index is empty.

**Comment by nghiahhnguyen** [comment]
Hi, thanks for checking in. I met the same problem, and I was not able to find what the cause is too, which is weird because simple GCN and GAT works just fine. Sorry for not being able to help with the problem.

**Comment by KomachiZ** [comment]
yeah,I think there are something wrong with GraphSage's structure ,like "message"and"update"functions where do not have the "Relu" and "concat" codes or  todo.I decide to reference the codes in original paper. Last, hope you get a greater academic  progress.
